### ISSUE TITLE
Proper naming of exported .md files

### ISSUE THREAD

**Issue by textortexxel** [danseethaler/dayone-to-md#2]
Currently, dayone-to-md gives entries names based on their internal IDs. These IDs make finding specific entries without looking into them impossible; when exporting a large enough journal, this becomes a problem. 

I think it would be good to have entries named following some sensible convention, such as YYYYMMDD{up to n allowed symbols from the first user-produced line}.md – this would also enable alphabetic sorting. Other, simpler options are also better than default IDs.

**Comment by danseethaler** [comment]
Thanks for the explanation @textortexxel! I think this is a great idea. I used the id for simplicity but I think it makes more sense to have a more human friendly file name. I'll try to take a look at this sometime this week.

**Comment by danseethaler** [comment]
@textortexxel just published version `0.0.3` on npm which includes this fix. Thanks for pointing it out!
